spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USERBLOG-SERVICE
          uri: lb://USERBLOG-SERVICE
          predicates:
          - Path=/users/**
         # filters:
          #  - name: CircuitBreaker
           #   args:
            #    name: USERBLOG-SERVICE
             #   fallbackuri: forward:/userservicefallback
        - id: BLOG-SERVICE
          uri: lb://BLOG-SERVICE
          predicates:
            - Path=/blogs/**
          #filters:
           # - name: circuitbreaker
            #  args:
             #   name: BLOG-SERVICE
              #  fallbackuri: forward:/blogservicefallback



hystrix:
  command:
    fallbackmethod:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


server:
  port: 9191

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost